# Generated by Django 2.2.3 on 2019-07-31 08:20

from django.db import migrations, models
import django.db.models.deletion
import extra_apps.DjangoUeditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='产品类别')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='关键字')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='产品名')),
                ('desc', extra_apps.DjangoUeditor.models.UEditorField(default='', verbose_name='产品描述')),
                ('image', models.ImageField(default='products/default.jpg', upload_to='products/%Y%m', verbose_name='封面图')),
                ('author', models.CharField(default='开封宋通轴承有限责任公司', max_length=20, verbose_name='作者')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='热度')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='所属类别')),
                ('keywords', models.ManyToManyField(to='products.KeyWord', verbose_name='关键字')),
            ],
        ),
    ]
