# Generated by Django 2.2.3 on 2019-07-31 10:22

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190731_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to=products.models.path_and_rename, verbose_name='封面图'),
        ),
    ]
