# Generated by Django 2.2.3 on 2019-08-01 16:21

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190731_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='宋通轴承', max_length=20, verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章名')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容')),
                ('author', models.CharField(default='宋通轴承', max_length=20, verbose_name='作者')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='热度')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('keywords', models.ManyToManyField(blank=True, null=True, to='products.KeyWord', verbose_name='关键字')),
            ],
            options={
                'verbose_name': '技术支持',
                'verbose_name_plural': '技术支持',
            },
        ),
    ]
