# Generated by Django 2.2.3 on 2019-08-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190801_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Support',
            new_name='Case',
        ),
    ]
