# Generated by Django 2.2.3 on 2019-08-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190801_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brief',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='简单描述'),
        ),
    ]
