# Generated by Django 2.2.3 on 2019-08-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='brief',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='简单描述'),
        ),
    ]
