# Generated by Django 2.2.3 on 2019-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_case_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='brief',
            field=models.CharField(default='', max_length=100, verbose_name='简单描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brief',
            field=models.CharField(default='', max_length=100, verbose_name='简单描述'),
        ),
    ]
