# Generated by Django 2.2.3 on 2019-07-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, verbose_name='名称')),
                ('info', models.CharField(max_length=50, verbose_name='联系信息')),
            ],
            options={
                'verbose_name': '联系信息',
                'verbose_name_plural': '联系信息',
                'unique_together': {('title', 'info')},
            },
        ),
    ]
