# Generated by Django 2.2.3 on 2019-08-05 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_userask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userask',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='咨询时间'),
        ),
        migrations.AddField(
            model_name='userask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间'),
        ),
        migrations.AddField(
            model_name='userask',
            name='due_status',
            field=models.SmallIntegerField(choices=[(0, '未处理'), (1, '已处理')], default=0, verbose_name='咨询处理状态'),
        ),
    ]
