# Generated by Django 2.2.3 on 2019-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190805_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回复时间'),
        ),
    ]
